time = input ("enter a specific time ")
print ("It was " +time+ " o\'clock when I hears a knock at the door.")
items = input ("please enter an item in plural format ")
name = input("please enter a name ")
print  ("I opened the door and there was a box full of "+ items +" with a note saying From \" " + name.capitalize() +"\".")
scream = input ("any sentence you would say when furious ")
print ("Just as I closed the door I heard a scream \"" + scream.upper() + "\".")
action = input ("write any verb ")
print ("I froze in place and all I could do was " + action +".")
